/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopAnimeRouteImport } from './routes/topAnime'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodeEpisodeIdRouteImport } from './routes/episode/$episodeId'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime/$animeId'

const TopAnimeRoute = TopAnimeRouteImport.update({
  id: '/topAnime',
  path: '/topAnime',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeEpisodeIdRoute = EpisodeEpisodeIdRouteImport.update({
  id: '/episode/$episodeId',
  path: '/episode/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/topAnime': typeof TopAnimeRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/topAnime': typeof TopAnimeRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/topAnime': typeof TopAnimeRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/episode/$episodeId': typeof EpisodeEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/topAnime'
    | '/anime/$animeId'
    | '/episode/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/topAnime' | '/anime/$animeId' | '/episode/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/topAnime'
    | '/anime/$animeId'
    | '/episode/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TopAnimeRoute: typeof TopAnimeRoute
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  EpisodeEpisodeIdRoute: typeof EpisodeEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topAnime': {
      id: '/topAnime'
      path: '/topAnime'
      fullPath: '/topAnime'
      preLoaderRoute: typeof TopAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$episodeId': {
      id: '/episode/$episodeId'
      path: '/episode/$episodeId'
      fullPath: '/episode/$episodeId'
      preLoaderRoute: typeof EpisodeEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TopAnimeRoute: TopAnimeRoute,
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  EpisodeEpisodeIdRoute: EpisodeEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
